//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool correctlyEnded {
            get {
                return ((bool)(this["correctlyEnded"]));
            }
            set {
                this["correctlyEnded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LP_ZK {
            get {
                return ((int)(this["LP_ZK"]));
            }
            set {
                this["LP_ZK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LP_Z {
            get {
                return ((int)(this["LP_Z"]));
            }
            set {
                this["LP_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LP_R {
            get {
                return ((int)(this["LP_R"]));
            }
            set {
                this["LP_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LP_P {
            get {
                return ((int)(this["LP_P"]));
            }
            set {
                this["LP_P"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PP_ZK {
            get {
                return ((int)(this["PP_ZK"]));
            }
            set {
                this["PP_ZK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PP_Z {
            get {
                return ((int)(this["PP_Z"]));
            }
            set {
                this["PP_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PP_R {
            get {
                return ((int)(this["PP_R"]));
            }
            set {
                this["PP_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PP_P {
            get {
                return ((int)(this["PP_P"]));
            }
            set {
                this["PP_P"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LZ_ZK {
            get {
                return ((int)(this["LZ_ZK"]));
            }
            set {
                this["LZ_ZK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LZ_Z {
            get {
                return ((int)(this["LZ_Z"]));
            }
            set {
                this["LZ_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LZ_R {
            get {
                return ((int)(this["LZ_R"]));
            }
            set {
                this["LZ_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LZ_P {
            get {
                return ((int)(this["LZ_P"]));
            }
            set {
                this["LZ_P"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PZ_ZK {
            get {
                return ((int)(this["PZ_ZK"]));
            }
            set {
                this["PZ_ZK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PZ_Z {
            get {
                return ((int)(this["PZ_Z"]));
            }
            set {
                this["PZ_Z"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PZ_R {
            get {
                return ((int)(this["PZ_R"]));
            }
            set {
                this["PZ_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PZ_P {
            get {
                return ((int)(this["PZ_P"]));
            }
            set {
                this["PZ_P"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LP_ZK_default {
            get {
                return ((int)(this["LP_ZK_default"]));
            }
            set {
                this["LP_ZK_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LP_Z_default {
            get {
                return ((int)(this["LP_Z_default"]));
            }
            set {
                this["LP_Z_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LP_R_default {
            get {
                return ((int)(this["LP_R_default"]));
            }
            set {
                this["LP_R_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LP_P_default {
            get {
                return ((int)(this["LP_P_default"]));
            }
            set {
                this["LP_P_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PP_ZK_default {
            get {
                return ((int)(this["PP_ZK_default"]));
            }
            set {
                this["PP_ZK_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PP_Z_default {
            get {
                return ((int)(this["PP_Z_default"]));
            }
            set {
                this["PP_Z_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PP_R_default {
            get {
                return ((int)(this["PP_R_default"]));
            }
            set {
                this["PP_R_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PP_P_default {
            get {
                return ((int)(this["PP_P_default"]));
            }
            set {
                this["PP_P_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LZ_ZK_default {
            get {
                return ((int)(this["LZ_ZK_default"]));
            }
            set {
                this["LZ_ZK_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LZ_Z_default {
            get {
                return ((int)(this["LZ_Z_default"]));
            }
            set {
                this["LZ_Z_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LZ_R_default {
            get {
                return ((int)(this["LZ_R_default"]));
            }
            set {
                this["LZ_R_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LZ_P_default {
            get {
                return ((int)(this["LZ_P_default"]));
            }
            set {
                this["LZ_P_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PZ_ZK_default {
            get {
                return ((int)(this["PZ_ZK_default"]));
            }
            set {
                this["PZ_ZK_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PZ_Z_default {
            get {
                return ((int)(this["PZ_Z_default"]));
            }
            set {
                this["PZ_Z_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PZ_R_default {
            get {
                return ((int)(this["PZ_R_default"]));
            }
            set {
                this["PZ_R_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PZ_P_default {
            get {
                return ((int)(this["PZ_P_default"]));
            }
            set {
                this["PZ_P_default"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public uint P_maxVelocity {
            get {
                return ((uint)(this["P_maxVelocity"]));
            }
            set {
                this["P_maxVelocity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public uint P_aceleration {
            get {
                return ((uint)(this["P_aceleration"]));
            }
            set {
                this["P_aceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public uint P_deceleration {
            get {
                return ((uint)(this["P_deceleration"]));
            }
            set {
                this["P_deceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public uint P_positionVelocity {
            get {
                return ((uint)(this["P_positionVelocity"]));
            }
            set {
                this["P_positionVelocity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public uint P_positionAceleration {
            get {
                return ((uint)(this["P_positionAceleration"]));
            }
            set {
                this["P_positionAceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public uint P_positionDeceleration {
            get {
                return ((uint)(this["P_positionDeceleration"]));
            }
            set {
                this["P_positionDeceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public uint R_positionVelocity {
            get {
                return ((uint)(this["R_positionVelocity"]));
            }
            set {
                this["R_positionVelocity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public uint R_positionAceleration {
            get {
                return ((uint)(this["R_positionAceleration"]));
            }
            set {
                this["R_positionAceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public uint R_positionDeceleration {
            get {
                return ((uint)(this["R_positionDeceleration"]));
            }
            set {
                this["R_positionDeceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint Z_positionVelocity {
            get {
                return ((uint)(this["Z_positionVelocity"]));
            }
            set {
                this["Z_positionVelocity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public uint Z_positionAceleration {
            get {
                return ((uint)(this["Z_positionAceleration"]));
            }
            set {
                this["Z_positionAceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public uint Z_positionDeceleration {
            get {
                return ((uint)(this["Z_positionDeceleration"]));
            }
            set {
                this["Z_positionDeceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public uint ZK_positionVelocity {
            get {
                return ((uint)(this["ZK_positionVelocity"]));
            }
            set {
                this["ZK_positionVelocity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public uint ZK_positionAceleration {
            get {
                return ((uint)(this["ZK_positionAceleration"]));
            }
            set {
                this["ZK_positionAceleration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public uint ZK_positionDeceleration {
            get {
                return ((uint)(this["ZK_positionDeceleration"]));
            }
            set {
                this["ZK_positionDeceleration"] = value;
            }
        }
    }
}
